// flow-typed signature: e9f56ad287aab5be57641fde1949749b
// flow-typed version: <<STUB>>/d3-state-visualizer_v^1.3.1/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'd3-state-visualizer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'd3-state-visualizer' {
    declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'd3-state-visualizer/dist/d3-state-visualizer' {
    declare module.exports: any;
}

declare module 'd3-state-visualizer/dist/d3-state-visualizer.min' {
    declare module.exports: any;
}

declare module 'd3-state-visualizer/lib/charts/index' {
    declare module.exports: any;
}

declare module 'd3-state-visualizer/lib/charts/tree/sortAndSerialize' {
    declare module.exports: any;
}

declare module 'd3-state-visualizer/lib/charts/tree/tree' {
    declare module.exports: any;
}

declare module 'd3-state-visualizer/lib/charts/tree/utils' {
    declare module.exports: any;
}

declare module 'd3-state-visualizer/lib/index' {
    declare module.exports: any;
}

declare module 'd3-state-visualizer/src/charts/index' {
    declare module.exports: any;
}

declare module 'd3-state-visualizer/src/charts/tree/sortAndSerialize' {
    declare module.exports: any;
}

declare module 'd3-state-visualizer/src/charts/tree/tree' {
    declare module.exports: any;
}

declare module 'd3-state-visualizer/src/charts/tree/utils' {
    declare module.exports: any;
}

declare module 'd3-state-visualizer/src/index' {
    declare module.exports: any;
}

// Filename aliases
declare module 'd3-state-visualizer/dist/d3-state-visualizer.js' {
    declare module.exports: $Exports<'d3-state-visualizer/dist/d3-state-visualizer'>;
}
declare module 'd3-state-visualizer/dist/d3-state-visualizer.min.js' {
    declare module.exports: $Exports<'d3-state-visualizer/dist/d3-state-visualizer.min'>;
}
declare module 'd3-state-visualizer/lib/charts/index.js' {
    declare module.exports: $Exports<'d3-state-visualizer/lib/charts/index'>;
}
declare module 'd3-state-visualizer/lib/charts/tree/sortAndSerialize.js' {
    declare module.exports: $Exports<'d3-state-visualizer/lib/charts/tree/sortAndSerialize'>;
}
declare module 'd3-state-visualizer/lib/charts/tree/tree.js' {
    declare module.exports: $Exports<'d3-state-visualizer/lib/charts/tree/tree'>;
}
declare module 'd3-state-visualizer/lib/charts/tree/utils.js' {
    declare module.exports: $Exports<'d3-state-visualizer/lib/charts/tree/utils'>;
}
declare module 'd3-state-visualizer/lib/index.js' {
    declare module.exports: $Exports<'d3-state-visualizer/lib/index'>;
}
declare module 'd3-state-visualizer/src/charts/index.js' {
    declare module.exports: $Exports<'d3-state-visualizer/src/charts/index'>;
}
declare module 'd3-state-visualizer/src/charts/tree/sortAndSerialize.js' {
    declare module.exports: $Exports<'d3-state-visualizer/src/charts/tree/sortAndSerialize'>;
}
declare module 'd3-state-visualizer/src/charts/tree/tree.js' {
    declare module.exports: $Exports<'d3-state-visualizer/src/charts/tree/tree'>;
}
declare module 'd3-state-visualizer/src/charts/tree/utils.js' {
    declare module.exports: $Exports<'d3-state-visualizer/src/charts/tree/utils'>;
}
declare module 'd3-state-visualizer/src/index.js' {
    declare module.exports: $Exports<'d3-state-visualizer/src/index'>;
}
